### ISSUE TITLE
Certificate API - Delete/recover/purge certificates

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#478]
### Done criteria
- Delete certificate API implemented
- Get deleted certificate API implemented
- Get deleted certificates API implemented
- Recover deleted certificate API implemented
- Purge deleted certificate API implemented
- Delete certificate operation API implemented
- Tests maintained/extended
- Documentation updated

### Tasks
- [x] Controller endpoint
  - [x] Delete certificate
  - [x] Get deleted certificate
  - [x] Get deleted certificates
  - [x] Recover deleted certificate
  - [x] Purge deleted certificate
  - [x] Delete certificate operation
- [x] Service changes (delete/recover/purge all linked managed entities as well)
- [x] Tests
  - [x] Unit tests
    - [x] For controller endpoints
    - [x] For service methods
  - [x] End-2-end tests
- [x] Documentation updated

### Notes
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/delete-certificate/delete-certificate
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/get-deleted-certificate/get-deleted-certificate
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/get-deleted-certificates/get-deleted-certificates
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/recover-deleted-certificate/recover-deleted-certificate
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/purge-deleted-certificate/purge-deleted-certificate
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/delete-certificate-operation/delete-certificate-operation
