### ISSUE TITLE
Certificate API - Lifetime action policy model

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#480]
### Done criteria
1. Lifetime policy model is saved and returned when requested
2. No lifetime action performed automatically
3. Test maintenance
4. Documentation update

### Tasks
- [x] Implement model classes
- [x] Implement entity classes
- [x] Implement mappers between models and entities
- [x] Use model classes
  - [x] At creation
  - [x] At import
  - [x] For get calls
- [x] Add new test cases
  - [x] Unit tests
  - [x] End-2-end tests
- [x]  Update documentation

### Out of scope
- Certificate renewal
