### ISSUE TITLE
Certificate API - Lifetime action policy execution

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#481]
### Done criteria
1. Certificate renewal implemented
2. Timeshift API change to accept cert regeneration parameter as extra
3. Timeshift implemented for certificates
    1. Automatic regeneration if requested of "original" certificate with updated dates
    2. Automatic generation of new certificate version to simulate renew lifetime action
4. Test maintenance
5. Documentation update

### Tasks
- [x] Implement renewal in service
- [x] Call renewal based on lifetime policy during timeshift
- [x] Implement regeneration in service
- [x] Add new parameters to timeshift API
- [x] Update management client
- [x] Call regeneration when timeshift requires it
- [x] Add new test cases
  - [x] Unit/Integration tests
  - [x] End-2-end tests
- [x]  Update documentation

### Dependencies
- Depends on #480
