### ISSUE TITLE
Certificate API - Update certificate/certificate policy

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#501]
### Done criteria
1. Update certificate API endpoint implemented
2. Update certificate policy API endpoint implemented
3. Covered with tests
4. Documentation updated

### Tasks
- [x] Controller methods created
  - [x] Update certificate API endpoint
  - [x] Update certificate policy API endpoint
- [x] Covered with tests
  - [x] UT/IT
  - [x] End-2-end
- [x] Documentation updated

### Notes
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/update-certificate/update-certificate?tabs=HTTP
  - Only updates enabled and tags
- https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/update-certificate-policy/update-certificate-policy?tabs=HTTP
  - Only updates properties in issuance policy but does not generate new certificate
