### ISSUE TITLE
Certificate API - Follow Key Vault behavior more accurately

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#503]
### Done criteria
1. Defaults are adjusted to mimic Key Vault behavior for
    1. key usages
    2. extended key usages
    3. lifetime actions
2. IPS are renamed to UPNS in SANS
3. Import functionality is updated to
    1. Match policy data instead of overriding it
    2. Allow importing self-signed certificate with auto-renew lifetime action
6. Certificate policy and issuance policy related fields are renamed to better reflect their meanings
7. Get certificate policy endpoint is fixed to return issuance policy data
8. Content type can be changed in issuance policy (and will be used on next renewal)
9. Tests are updated

### Tasks
- [x] Update defaults
- [x] Rename UPNS
- [x] Fix import
- [x] Fix issuance policy naming
- [x] Fix certificate policy naming
- [x] Fix get certificate policy endpoint behavior
- [ ] Update tests
