### ISSUE TITLE
Reduce the amount of converter injections in controllers

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/lowkey-vault#506]
### Done criteria
1. Converters are grouped by API version and function
2. Converter holders are created for each group
3. A single dependency is injected into controllers providing all necessary converters
4. Generic controller implementations are revised, mapping logic is moved to new converters where necessary
5. Tests updated

### Tasks
- [x] Converter groups created
- [x] Converter injections are replaced with groups
- [x] Reusability is reviewed and enhanced in controllers
- [x] Mapping logic extracted/moved from controllers where necessary
- [x] Tests updated
