### ISSUE TITLE
DefaultAzureCredential

### ISSUE THREAD

**Issue by BartNetJS** [nagyesta/lowkey-vault#611]
Nice work!

One thing I'm struggling with to find a descent solution is the DefaultAzureCredential
I see a example to use the NoopCredentials provider.
But it mean that there is at some place conditional code...
I like to keep the code as clean as possible
Ideal would be also a mock service for the DefaultAzureCredential

**Comment by nagyesta** [comment]
Hi @BartNetJS ,
thank you for your feedback! I think the same, the ideal solution would be using the DefaultAzureCredential, but I have not managed to figure it out yet. Not even sure I ever will! Anyway, it is something that is annoying me too, so if it can be solved, I will do my best to get it working eventually.

**Comment by nagyesta** [comment]
Hi,
I started to look into this yesterday and I might have a lead. Basically I have created a container with the 169.254.169.254 IP that is used by the Azure side car component that is handling managed identity. I have managed to confuse the DefaultAzureCredential enough to accept a dummy token from this container and forward it to Lowkey Vault for authentication.

This was verified so far with Go, Python and Java. I will check .Net and NodeJS as well, then I will figure out how to create a proper container from this prototype. I will continue to post updates here.

**Comment by nagyesta** [comment]
### Tasks

- [ ] Create proototype
- [ ] Verify that prototype can work with
  - [ ] Go
  - [ ] Python
  - [ ] Java
  - [ ] .Net
  - [ ] NodeJS
- [ ] Create final artifact based on prototype
- [ ] Add new examples to the example projects to demonstrate both options (with or without the managed identity)
  - [ ] Java
  - [ ] Python
  - [ ] Go
  - [ ] .Net
  - [ ] NodeJS
  - [ ] Docker
- [ ] Update documentation

**Comment by nagyesta** [comment]
### Note

The working prototype I have used:

```bash
docker network create --subnet=169.254.169.0/24 azure-sidecar
docker run --net azure-sidecar --ip 169.254.169.254 --rm hashicorp/http-echo -listen=:80 -text='{"access_token":"dummy","refresh_token":"none","expires_in":3600,"expires_on":36000,"token_type":1,"resource":"https://localhost:8443"}'
```

**Comment by nagyesta** [comment]
Just pushed the initial version of this artifact to this repository: https://github.com/nagyesta/assumed-identity
Docker container images can be found here: https://hub.docker.com/r/nagyesta/assumed-identity

**Comment by nagyesta** [comment]
Updated: https://github.com/nagyesta/lowkey-vault/wiki/Example:-How-can-you-use-Lowkey-Vault-in-your-tests#5-authentication

**Comment by nagyesta** [comment]
Hi @BartNetJS ,
I think I have managed to complete this task. As mentioned above, the Managed Identity implementation of DefaultAzureCredential is pretty forgiving about the kinds of tokens IMDS is providing. So I have created a new container, Assumed Identity to fake IMDS as well and provide dummy tokens. 

On a local machine, I would recommend to follow the guide [here](https://github.com/nagyesta/assumed-identity#starting-the-container-on-a-developer-machine). This way you don't need any additional configuration on the app side.

On CI, assuming that your CI agent/runner is on an Azure VM as well, this will most probably not work, so you need to run Assumed Identity with the steps listed [here](https://github.com/nagyesta/assumed-identity#starting-the-container-on-a-developer-machine) instead and set the env variables which will ask the Azure client to call it instead of the default location. Please take a look at the PRs above to see working examples for each supported language!

I hope this solves your issue, but would like to hear your opinion! Do you think this can work for you?

Thank you in advance!

**Comment by BartNetJS** [comment]
hi @nagyesta , great job! I will have a look at it.

**Comment by nagyesta** [comment]
Hi @BartNetJS , 
I don't mean to hurry you, just wanted to ask to please let me know about the results so that I can close the ticket.
Thank you!

**Comment by nagyesta** [comment]
Hi, 
assuming, that the issue is solved, so I am closing it. Please feel free to reopen or open a new one if not.
Thank you, and best of luck!
